(function(){
'use strict';CindyJS.registerPlugin(1,"symbolic",function(g){function k(a){if(null==a||"object"!=typeof a)return a;if(a instanceof Array){var b=[];for(var c=0,m=a.length;c<m;c++)b[c]=k(a[c]);return b}if(a instanceof Object){b={};for(c in a)a.hasOwnProperty(c)&&0<="oper impl args ctype stack name arglist value real imag key obj body".split(" ").indexOf(c)&&(b[c]=k(a[c]));a.modifs&&(b.modifs=a.modifs);return b}}var d=function(a){return{ctype:"number",value:{real:a,imag:0}}},e=function(a,b){return{ctype:"function",
oper:a,args:b,modifs:{}}},x={sin$1:function(a){return[e("cos$1",[a[0]])]},cos$1:function(a){return[e("sub$2",[d(0),e("sin$1",[a[0]])])]},exp$1:function(a){return[e("exp$1",[a[0]])]},log$1:function(a){return[e("div$2",[d(1),a[0]])]},sqrt$1:function(a){return[e("div$2",[d(.5),e("sqrt$1",[a[0]])])]},add$2:function(a){return[d(1),d(1)]},sub$2:function(a){return[d(1),d(-1)]},mult$2:function(a){return[a[1],a[0]]},div$2:function(a){return[e("div$2",[d(1),a[1]]),e("div$2",[e("sub$2",[d(0),a[0]]),e("mult$2",
[a[1],a[1]])])]},pow$2:function(a){return[e("mult$2",[a[1],e("pow$2",[a[0],e("sub$2",[a[1],d(1)])])]),e("mult$2",[e("log$1",[a[0]]),e("pow$2",[a[0],a[1]])])]},";":function(a){return"void"==a[1].ctype?[d(1),d(0)]:[d(0),d(1)]}},y={sin$1:function(a,b){return Infinity},cos$1:function(a,b){return Infinity},exp$1:function(a,b){return Infinity},log$1:function(a,b){return Infinity},sqrt$1:function(a,b){return Infinity},add$2:function(a,b){return Math.max(f(a[0],b),f(a[1],b))},sub$2:function(a,b){return Math.max(f(a[0],
b),f(a[1],b))},mult$2:function(a,b){return f(a[0],b)+f(a[1],b)},div$2:function(a,b){return 0===f(a[1],b)?f(a[0],b):Infinity},pow$2:function(a,b){return 0===f(a[1],b)?f(a[0],b)*g.evaluate(a[1]).value.real:Infinity},";":function(a,b){if("void"===a[1].ctype)return f(a[0],b);g.evaluate(a[0]);return f(a[1],b)}},t={"+":"add$2","-":"sub$2","*":"mult$2","/":"div$2","^":"pow$2"},r=function(a,b){if("variable"===a.ctype&&b[a.name])return b[a.name];a.args&&(a.args=a.args.map(function(c){return r(c,b)}));return a},
h=function(a,b){return a&&"number"===a.ctype&&0===a.value.imag&&a.value.real===b},q=function(a){if(a.args&&(a.args=a.args.map(q),a.args.every(function(b){return"number"===b.ctype})))return g.evaluate(a);if("add$2"===a.oper||"+"===a.oper){if(h(a.args[0],0))return a.args[1];if(h(a.args[1],0))return a.args[0]}else if("sub$2"===a.oper||"-"===a.oper){if(h(a.args[1],0))return a.args[0]}else if("mult$2"===a.oper||"*"===a.oper){if(h(a.args[0],0)||h(a.args[1],0))return d(0);if(h(a.args[0],1))return a.args[1];
if(h(a.args[1],1))return a.args[0]}else if(("pow$2"===a.oper||"^"===a.oper)&&h(a.args[1],1))return a.args[0];return a},v=function(a,b){if("variable"===a.ctype)return b[a.name]?b[a.name]:d(0);if("number"===a.ctype)return d(0);if("infix"===a.ctype||"function"===a.ctype){var c=g.getMyfunction(a.oper),m=d(0),p={};if(c)for(var n in a.args)p[c.arglist[n].name]=a.args[n];for(var u in a.args){n=v(a.args[u],b);var l=d(0);h(n,0)||(c?(l={},l[c.arglist[u].name]=d(1),l=r(k(v(k(c.body),l)),p)):x[t[a.oper]||a.oper]&&
(l=x[t[a.oper]||a.oper](a.args)[u]),h(l,0)||(h(n,1)||(l=e("mult$2",[l,n])),m=h(m,0)?l:e("add$2",[m,l])))}return m}console.error("Do not know how to differentiate:");console.log(a);return d(0)},f=function(a,b){if("variable"===a.ctype)return b[a.name]?b[a.name]:0;if("number"===a.ctype)return 0;if("infix"===a.ctype||"function"===a.ctype){if(";"!=a.oper&&a.args.every(function(n){return 0===f(n,b)}))return 0;var c=g.getMyfunction(a.oper);if(c){var m={},p;for(p in a.args)m[c.arglist[p].name]=f(a.args[p],
b);return f(q(k(c.body)),m)}if(c=y[t[a.oper]||a.oper])return c(a.args,b)}else if("void"===a.ctype)return 0;console.log("Do not know how to compute the degree of:");console.log(a);return Infinity};g.defineFunction("diff",3,function(a,b){b={};if(!a[1].name)return g.nada;b[a[1].name]=d(1);b=q(v(k(a[0]),b));return g.evaluate(r(k(a[2]),{"#":b}))});g.defineFunction("simplify",2,function(a,b){return g.evaluate(r(k(a[1]),{"#":q(k(a[0]))}))});for(var z=function(a,b){b={};for(var c in a)if(1<=c)if("variable"===
a[c].ctype)b[a[c].name]=1;else return g.nada;a=f(q(k(a[0])),b);Infinity==a&&(a=-1);return d(a)},w=1;3>=w;w++)g.defineFunction("degree",1+w,z)});
}).call(this);//# sourceMappingURL=symbolic.js.map

